/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DiaryEntry = IDL.Record({
  'date' : IDL.Text,
  'mood' : IDL.Text,
  'reflection' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDiaryEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllMotivationalMessages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyEntries' : IDL.Func([], [IDL.Vec(DiaryEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DiaryEntry = IDL.Record({
    'date' : IDL.Text,
    'mood' : IDL.Text,
    'reflection' : IDL.Text,
  });
  
  return IDL.Service({
    'addDiaryEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllMotivationalMessages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyEntries' : IDL.Func([], [IDL.Vec(DiaryEntry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };